#!/bin/bash

#set -x

XML=$1

if test -z "$XML"; then
	echo "Usage: $0 XMLFILE"
	exit 1
fi

if test -z "`head -n 2 \"$XML\" | tail -n 2 | grep property-set`"; then
	echo "Aborting: '$XML' seems not to have <property-set ...> on the second line"
	exit 1
fi

if test -z "`ex --version | grep VIM`"; then
	echo "Aborting: Vim not installed"
	exit 1
fi

EXPROG='2
c
<property-set xmlns="http://mcc.lip6.fr/">
.
wq
'
echo "$EXPROG" | ex "$XML"

echo "After fix $XML:"
grep -n -m 1 "property-set" "$XML"
