#!/bin/bash

run_benchmark ()
{
	# runs the benchkit_head script on $MODEL and $EXAM

	echo "rit: MODEL=$MODEL" >&2
	echo "rit: EXAM=$EXAM" >&2

	BKHOME=~/BenchKit
	TMP=/tmp/run

	mkdir -p "$TMP"
	cd "$TMP"
	#rm -Rf "$MODEL"
	tar xzf "$BKHOME/INPUTS/$MODEL.tgz"
	cd "$MODEL"
	echo "rit: PWD $PWD" >&2
	export BK_EXAMINATION="$EXAM"
	export BK_TOOL=cunf
	"$BKHOME"/BenchKit_head.sh
}

########################

# Usage: runit [MODEL [EXAMINATION]]

if [ "$#" = 2 ]; then
	MODEL="$1"
	EXAM="$2"
else
	NRM=`cat doc/models-1 | grep -v '^#' | wc -l`
	NRE=`cat doc/exams | grep -v '^#' | wc -l`
	M=`echo "($RANDOM % $NRM) + 1" | bc`
	E=`echo "($RANDOM % $NRE) + 1" | bc`
	MODEL=`cat doc/models-1 | grep -v '^#' | head -n$M | tail -n1`
	EXAM=`cat doc/exams | grep -v '^#' | head -n$E | tail -n1`
fi
if [ "$#" = 1 ]; then
	MODEL="$1"
fi

run_benchmark

# - /tmp/run/ResAllocation-PT-R020C002, ReachabilityFireability has mixture
#   of results :)
# - MODEL=SharedMemory-PT-000050 produces a crash in cunf
# - MODEL=GlobalResAllocation-PT-03 has weighted arcs

#MODEL=SharedMemory-PT-000050
#MODEL=/tmp/run/HouseConstruction-PT-050 # unsafe
#MODEL=Dekker-PT-020 # transition id != transition name
#MODEL=CSRepetitions-PT-03
#EXAM=ReachabilityDeadlock
#EXAM=ReachabilityFireabilitySimple
#EXAM=ReachabilityFireability

