#!/bin/bash

timeit ()
{
	/usr/bin/time -l -- $* 2> ri.time
	WALLTIME=$(head -n1 ri.time | sed 's/real.*//g;s/ //g')s
	M=$(head -n2 ri.time | tail -n1 | sed 's/max.*//g;s/ //g')
	MAXRSS=$(($M / 1024 / 1024))MB
}

########################

# Usage: runit [MODEL [EXAMINATION]]

if [ "$#" = 2 ]; then
	MODEL="$1"
	EXAM="$2"
else
	NRM=`cat doc/models-1 | grep -v '^#' | wc -l`
	NRE=`cat doc/exams | grep -v '^#' | wc -l`
	M=`echo "($RANDOM % $NRM) + 1" | bc`
	E=`echo "($RANDOM % $NRE) + 1" | bc`
	MODEL=`cat doc/models-1 | grep -v '^#' | head -n$M | tail -n1`
	EXAM=`cat doc/exams | grep -v '^#' | head -n$E | tail -n1`
fi
if [ "$#" = 1 ]; then
	MODEL="$1"
fi

# - /tmp/run/ResAllocation-PT-R020C002, ReachabilityFireability has mixture
#   of results :)
# - MODEL=SharedMemory-PT-000050 produces a crash in cunf

#MODEL=SharedMemory-PT-000050
#MODEL=/tmp/run/HouseConstruction-PT-050 # unsafe
#MODEL=Dekker-PT-020 # transition id != transition name
#MODEL=CSRepetitions-PT-03
#EXAM=ReachabilityDeadlock
#EXAM=ReachabilityFireabilitySimple
#EXAM=ReachabilityFireability


echo "rit: MODEL=$MODEL"
echo "rit: EXAM=$EXAM"

BKHOME=/tmp/benchkit
TMP=/tmp/run

mkdir -p "$TMP"
cd "$TMP"
rm -Rf "$MODEL"
tar xzf "$BKHOME/INPUTS/$MODEL.tgz"
cd "$MODEL"
echo "rit: PWD $PWD"
export BK_EXAMINATION="$EXAM"
export BK_TOOL=cunf
timeit "$BKHOME"/BenchKit_head.sh
echo "rit: overall : time $WALLTIME maxrss $MAXRSS" >> ri.times
echo "================"
cat ri.times
echo "======================================================"
